kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ckad-cluster
nodes:
- role: control-plane
  labels:
    tier: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP  
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=16Gi,cpu=12        
- role: worker           
- role: worker
  labels:
    tier: worker-one 
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=16Gi,cpu=12     
- role: worker
  labels:
    tier: worker-two
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: memory=16Gi,cpu=12    
